# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: ElectronicTheatreControls.EosFamily
PackageVersion: 3.3.0.549
PackageLocale: en-US
Publisher: Electronic Theatre Controls, Inc.
PackageName: Eos Family
PackageUrl: https://www.etcconnect.com/eos-software/
License: Proprietary
ShortDescription: A suite of software that allows you to interact with Eos hardware.
Tags:
- etcconnect
- electronictheatrecontrols
- element2
- augment3dtether
- lightingeffects
- productiondashboard
- consolesoftware
ManifestType: defaultLocale
ManifestVersion: 1.10.0