# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Acer.AcerSense.ARM64
PackageVersion: 5.0.2068
PackageLocale: en-US
Publisher: Acer
PackageName: AcerSense (ARM64)
# PackageUrl: https://www.acer.com/gb-en/support/product-support/Swift%20SFG16-A71/downloads
License: Proprietary
ShortDescription: A versatile application that lets you access all of your device's AI features in one place. Monitor your device's performance, optimize battery settings, perform a device health checkup, and more with the AcerSense application.
Moniker: acersensearm64
Tags:
- acersense-arm64
- acer-sense-arm64
- acer-app-center
- 9nt9vkd8qcw7
ManifestType: defaultLocale
ManifestVersion: 1.12.0