# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Acer.AcerSense.ARM64
PackageVersion: 5.0.2068
ReleaseDate: 2026-07-03
MinimumOSVersion: 10.0.14316.0
InstallerType: zip
Installers:
- Architecture: arm64
  NestedInstallerType: msix
  NestedInstallerFiles:
  - RelativeFilePath: 'AcerSense_Acer_5.0.2068_20260327_W11ARM64\AcerSense5_RC34_ARM_RC16_5.0.2068_only for 26H1\UWP\a785d212f8b44b0b81b694ed7e9a1a08.appx'
  InstallerUrl: https://global-download.acer.com/GDFiles/Application/AcerSense/AcerSense_Acer_5.0.2068_20260327_W11ARM64_A.zip?acerid=639186451301703638
  InstallerSha256: 4fa8f5516af302bf8bb928d0505817e13a1f3893cebd0bafe442a297d002c224
  SignatureSha256: 6e5f4a2f82f755b69eb47dceb0e5780d43e5d1cab3ca6875723bc596508808bd
  PackageFamilyName: ULICTekInc.AcerSense5.0_nt9dgb7efx6bt
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCLibs.Desktop.14
    MinimumVersion: 14.0.33728.0
ManifestType: installer
ManifestVersion: 1.12.0