# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: HP.App
PackageVersion: 57.5263.7882
ReleaseDate: 2026-06-15
InstallerType: exe
InstallerSwitches:
  Silent: /s
  SilentWithProgress: /s
Installers:
- Architecture: x64
  InstallerUrl: https://ftp.hp.com/pub/softpaq/sp173501-174000/sp173578.exe
  InstallerSha256: 7FD7E4987C00DFCF6B1F69864D18FAC023815DE25CC64EFAA1139B304EEEE967
  PackageFamilyName: AD2F1837.myHP_v10z8vjag6ke6
  AppsAndFeaturesEntries:
  - InstallerType: msix
    PackageFamilyName: AD2F1837.myHP_v10z8vjag6ke6
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.UI.Xaml.2.8
      MinimumVersion: 8.2310.30001.0
    - PackageIdentifier: Microsoft.DotNet.Native.Runtime
      MinimumVersion: 2.2.28604.0
    - PackageIdentifier: Microsoft.VCLibs.14
      MinimumVersion: 14.0.33519.0
    - PackageIdentifier: Microsoft.VCLibs.Desktop.14
      MinimumVersion: 14.0.33728.0
ManifestType: installer
ManifestVersion: 1.12.0