# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: HP.App
PackageVersion: 57.5263.7882
PackageLocale: en-US
Publisher: HP Inc.
PackageName: HP
# PackageUrl: https://support.hp.com/gb-en/drivers/swdetails/hp-elitebook-645-14-inch-g11-notebook-pc/2102139945/swItemId/ob-366475-1 (Likely to cause Winget pipeline HTTP errors)
License: Proprietary
Copyright: © 2026 HP Development Company, L.P.
ShortDescription: A UWP app that provides user access to PC settings and experiences. The app integrates HP applications into a single hub for hardware optimization, providing an intuitive source of enhanced management options for hardware, accessories, and services.
Moniker: hpapp
Tags:
- hp-app
- hp-laptops
- hp-printers
- hp-dockings
- hp-pens
- 9n9phdt62w94
ManifestType: defaultLocale
ManifestVersion: 1.12.0