# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: HP.App
PackageVersion: 57.5263.7882
PackageLocale: en-GB
ShortDescription: A UWP app that provides user access to PC settings and experiences. The app integrates HP applications into a single hub for hardware optimisation, providing an intuitive source of enhanced management options for hardware, accessories, and services.
ManifestType: locale
ManifestVersion: 1.12.0