# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Rojo.Rojo
PackageVersion: 7.7.0
ReleaseDate: 2026-07-02
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: rojo.exe
  PortableCommandAlias: rojo
UpgradeBehavior: uninstallPrevious
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/rojo-rbx/rojo/releases/download/v7.7.0/rojo-7.7.0-windows-x86_64.zip
  InstallerSha256: 2179C44862A10ECBD725BDFEB4ABC64E16DC4AAD9B6C8F3E1A7C46A87280B949
- Architecture: arm64
  InstallerUrl: https://github.com/rojo-rbx/rojo/releases/download/v7.7.0/rojo-7.7.0-windows-aarch64.zip
  InstallerSha256: f500d23ff2c3baa0cfc5a9a8c6456e49958b7123916f9e20df731c0e562b877f
  AppsAndFeaturesEntries:
  - DisplayName: Rojo (ARM64)
ManifestType: installer
ManifestVersion: 1.12.0
