# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: GIGABYTE.XTREMEENGINE
PackageVersion: 1.2.6.0
PackageLocale: en-US
Publisher: GIGABYTE Technology Co.,Inc.
PackageName: GIGABYTE XTREME ENGINE
License: Proprietary
Copyright: Copyright © 2016 GIGABYTE
ShortDescription: Overclock tool for certain GIGABYTE GPUs.
Tags:
- gvcidrv64.sys
- gvcidrv64.inf
- gpu
- graphics
- overclock
- giga-byte
ManifestType: defaultLocale
ManifestVersion: 1.10.0
