# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: OrryVerducci.TtxFromTS
PackageVersion: "2.0"
ReleaseDate: 2021-05-04
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: TtxFromTS.exe
  PortableCommandAlias: ttxfromts
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/orryverducci/TtxFromTS/releases/download/v2.0/win-x64.zip
  InstallerSha256: C91A3408943E96DD2CA6B827DE56ECD6015BDF4703D01349C5C74187DBBBFF49
- Architecture: x86
  InstallerUrl: https://github.com/orryverducci/TtxFromTS/releases/download/v2.0/win-x86.zip
  InstallerSha256: 7055defee030e886873f00b05cf269e95071ea74f3990a479e392d08afbc752c
  AppsAndFeaturesEntries:
  - DisplayName: TtxFromTS (x86)
- Architecture: arm64
  InstallerUrl: https://github.com/orryverducci/TtxFromTS/releases/download/v2.0/win-arm64.zip
  InstallerSha256: e669a6e8c27cd9175318ca5c0c3880876977c8dd86310cbd258237202fa7f29b
  AppsAndFeaturesEntries:
  - DisplayName: TtxFromTS (ARM64)
ManifestType: installer
ManifestVersion: 1.10.0
