# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
PackageIdentifier: bl00mber.alarm-cron
PackageVersion: 0.1.1
PackageLocale: en-US
Publisher: Nick Reiley
PublisherUrl: https://github.com/bl00mber
PublisherSupportUrl: https://github.com/bl00mber/alarm-cron/issues
PackageName: alarm-cron
PackageUrl: https://github.com/bl00mber/alarm-cron
License: ISC
LicenseUrl: https://github.com/bl00mber/alarm-cron/blob/master/LICENSE
ShortDescription: Create alerts, timers and stopwatches from the tray.
ReleaseNotesUrl: https://github.com/bl00mber/alarm-cron/releases/tag/v0.1.1
Moniker: alarm-cron
Tags:
- alarm-clock
- alarmclock
- alarmcron
- countdown
- stopwatch
- time
- time-management
- timer
ManifestType: locale
ManifestVersion: 1.12.0
