# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: garethgeorge.Backrest
PackageVersion: 1.14.1
ReleaseDate: 2026-07-12
InstallerLocale: en-US
Scope: user
InstallerSwitches:
  Custom: /CURRENTUSER
Installers:
- Architecture: x64
  InstallerType: inno
  ElevationRequirement: elevatesSelf
  InstallerUrl: https://github.com/garethgeorge/backrest/releases/download/v1.14.1/BackrestSetup-x86_64.exe
  InstallerSha256: C8E6669546BDA08B06F6A6EE6803544975B33413BC0B268BEB9E6263C778CC50
  ProductCode: Backrest_is1
  AppsAndFeaturesEntries:
  - DisplayName: Backrest 1.14.1
    ProductCode: Backrest_is1
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\Programs\Backrest'
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: backrest.exe
  ArchiveBinariesDependOnPath: true
  InstallerUrl: https://github.com/garethgeorge/backrest/releases/download/v1.14.1/backrest_Windows_arm64.zip
  InstallerSha256: C8E6669546BDA08B06F6A6EE6803544975B33413BC0B268BEB9E6263C778CC50
  AppsAndFeaturesEntries:
  - DisplayName: Backrest (Portable ARM64)
ManifestType: installer
ManifestVersion: 1.12.0
