# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: COAA.PlanePlotter
PackageVersion: 6.7.2.4
DefaultLocale: en-GB
ManifestType: version
ManifestVersion: 1.10.0
