# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: Acer.AcerSense.x64
PackageVersion: 5.0.2048
PackageLocale: en-GB
ShortDescription: A versatile application that lets you access all of your device's AI features in one place. Monitor your device's performance, optimise battery settings, perform a device health checkup, and more with the AcerSense application.
Tags:
- acersense-x64
- acersensex64
- acer-sense-x64
- acer-app-centre
- 9nt9vkd8qcw7
ManifestType: locale
ManifestVersion: 1.12.0