# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Acer.AcerSense.x64
PackageVersion: 5.0.2048
ReleaseDate: 2026-06-11
MinimumOSVersion: 10.0.14316.0
InstallerType: zip
Installers:
- Architecture: x64
  NestedInstallerType: msix
  NestedInstallerFiles:
  - RelativeFilePath: AcerSense_Acer_5.0.2048_W11x64\AcerSense5_RC32_5.0.2048\UWP\5390feaa9b8b4161911443c112886a3b.appx
  InstallerUrl: https://global-download.acer.com/GDFiles/Application/AcerSense/AcerSense_Acer_5.0.2048_W11x64_A.zip?acerid=639167638961325272
  InstallerSha256: 7aafbb95e46a26fbe7fab5cd45e17426974ae3b644dabd25189cdcd743e8adaf
  SignatureSha256: 61c9645c71c915f913e6b274c15f807c5d7eca989a1e7c90a5472df67a631867
  PackageFamilyName: ULICTekInc.AcerSense5.0_nt9dgb7efx6bt
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCLibs.Desktop.14
    MinimumVersion: 14.0.33728.0
ManifestType: installer
ManifestVersion: 1.12.0