# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Acer.AcerSense.x64
PackageVersion: 5.0.2048
PackageLocale: en-US
Publisher: Acer
PackageName: AcerSense (x64)
# PackageUrl: https://www.acer.com/gb-en/support/product-support/Swift%20SFG16-A71/downloads (Winget pipelines threw a connection error about it)
License: Proprietary
ShortDescription: A versatile application that lets you access all of your device's AI features in one place. Monitor your device's performance, optimize battery settings, perform a device health checkup, and more with the AcerSense application.
Moniker: acersense
Tags:
- acersense-x64
- acersensex64
- acer-sense-x64
- acer-app-center
- 9nt9vkd8qcw7
ManifestType: defaultLocale
ManifestVersion: 1.12.0
