# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.28.0.schema.json

PackageIdentifier: DualSenseClient.DualSenseClient
PackageVersion: 1.0.0-12
PackageLocale: en-GB
ShortDescription: "Unofficial DualSense client for Windows. Customise and monitor your PS5 DualSense controller: lighting, profiles, input monitoring, rumble, adaptive triggers, and audio to the controller's speaker and haptics."
ManifestType: locale
ManifestVersion: 1.28.0